### ISSUE TITLE
Use ./darknet detector demo get error

### ISSUE THREAD

**Issue by smallworld-network-wupeng** [shadowkane/darknet-nnpack-opencv4.0-raspicam#2]
```
Loading weights from yolov3-tiny-modify-288_final.weights...Done!
video file: tank_front_480_30.mov
Segmentation fault
```
I can use it in pc use darknet , but in raspberry get error.

**Comment by shadowkane** [comment]
Sorry for the late answer, i had to back again to the project since it's old and test it with a random video from youtube and it works fine, if i remember well, i had the same issue with some weight files and i had to look for the right one, it's just a raspberry pi, we can't compare it to a PC and expect too much from it, i think the PI 4 is much better if you want a good and fast predictions.
i added to the library the weight file i used in new folder "used_weight" check it and test it and tell me the result, hope it works for you.
best regard

**Comment by smallworld-network-wupeng** [comment]
Thank you , I use opencv 3.4.x the problem was gone
